version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: koishow-sql
    environment:
      SA_PASSWORD: "12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: KoiShow.APIService/Dockerfile
    container_name: koishow-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=FA24_SE1716_PRN231_G2_KOISHOW;uid=sa;pwd=12345;TrustServerCertificate=True"
    depends_on:
      - sqlserver

volumes:
  sql_data:
